import { useEffect, useRef, useState } from "react";
import ScrollReveal from "@/components/motion/ScrollReveal";

interface ClientLogo {
  name: string;
  src: string;
  description?: string;
}

const clients: ClientLogo[] = [
  {
    name: "Bupa",
    src: "/images/clients/Bupa.svg",
    description:
      "Led the modernization of data systems by moving legacy information into a high-performance cloud environment. This transition made it easier for the business to analyze insurance trends and manage internal reporting.",
  },
  {
    name: "CocaCola",
    src: "/images/clients/CocaCola.svg",
    description:
      "Acted as a bridge between various global business systems, bringing all data together into one unified view. This allowed the retail team to track sales, stock levels, and equipment performance more efficiently than ever before.",
  },
  {
    name: "Deloitte",
    src: "/images/clients/Deloitte.svg",
    description:
      "Built automated systems to collect and organize large amounts of information for corporate reporting. Implemented cost-effective ways to archive older data without losing easy access to it.",
  },
  {
    name: "Cognizant DOE",
    src: "/images/clients/Cognizant_DOE.svg",
    description:
      "Designed and led the move to a modern cloud-based system to ensure departmental data is handled reliably and securely. Focused on making information available in real-time, helping the department gain immediate insights through better reporting.",
  },
  {
    name: "Ladbrokes",
    src: "/images/clients/Ladbrokes.svg",
    description:
      "Managed the massive flow of information generated by billions of betting transactions. Turned this big data into easy-to-read visual dashboards that helped the business track performance.",
  },
  {
    name: "Debenhams",
    src: "/images/clients/Debenhams.svg",
  },
  {
    name: "NTTDATA",
    src: "/images/clients/NTTDATA.svg",
  },
  {
    name: "Tokio Marine",
    src: "/images/clients/Tokio_Marine_Logo.svg",
  },
  {
    name: "IFGL",
    src: "/images/clients/IFGL.svg",
  },
  {
    name: "Go Car Credit",
    src: "/images/clients/Go_Car_Credit.svg",
  },
  {
    name: "Howden",
    src: "/images/clients/Howden.svg",
  },
  {
    name: "RBC_Brewin",
    src: "/images/clients/RBC_Brewin.svg",
  },
  {
    name: "DHL",
    src: "/images/clients/DHL.svg",
  },
  {
    name: "BAT",
    src: "/images/clients/BAT.svg",
  },
  {
    name: "SoftwareOne",
    src: "/images/clients/SoftwareOne.svg",
  },
];

const TrustedBySection = () => {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [isPaused, setIsPaused] = useState(false);
  const animationRef = useRef<number>();
  const scrollPos = useRef(0);

  useEffect(() => {
    const container = scrollRef.current;
    if (!container) return;

    const speed = 0.5;

    const animate = () => {
      if (!isPaused && container) {
        scrollPos.current += speed;
        const halfWidth = container.scrollWidth / 2;
        if (scrollPos.current >= halfWidth) {
          scrollPos.current = 0;
        }
        container.style.transform = `translateX(-${scrollPos.current}px)`;
      }
      animationRef.current = requestAnimationFrame(animate);
    };

    animationRef.current = requestAnimationFrame(animate);
    return () => {
      if (animationRef.current) cancelAnimationFrame(animationRef.current);
    };
  }, [isPaused]);

  const allClients = [...clients, ...clients];

  return (
    <section className="border-y border-border bg-background py-14 md:py-20 overflow-hidden">
      <div className="container-narrow px-4 sm:px-6 lg:px-8">
        <ScrollReveal>
          <p className="mb-10 text-center text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">
            Trusted by leading organisations
          </p>
        </ScrollReveal>
      </div>

      <div
        className="relative px-4"
        onMouseEnter={() => setIsPaused(true)}
        onMouseLeave={() => setIsPaused(false)}
      >
        <div ref={scrollRef} className="flex gap-6 will-change-transform">
          {allClients.map((client, i) => (
            <div
              key={`${client.name}-${i}`}
              className={`flex-shrink-0 rounded-lg border border-border bg-white shadow-sm flex flex-col items-center ${
                client.description
                  ? "w-[280px] sm:w-[300px] md:w-[340px] min-h-[280px] p-5 md:p-6"
                  : "w-[180px] sm:w-[200px] md:w-[220px] min-h-[120px] p-5 md:p-6 justify-center"
              }`}
            >
              <div
                className={`flex items-center justify-center w-full ${
                  client.description ? "h-16 md:h-20 mb-4" : "h-16 md:h-20"
                }`}
              >
                <img
                  src={client.src}
                  alt={client.name}
                  className="max-h-full max-w-[80%] object-contain"
                  loading="lazy"
                />
              </div>
              {client.description && (
                <p className="text-xs leading-relaxed text-muted-foreground text-justify mt-auto">
                  {client.description}
                </p>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default TrustedBySection;
